name: Sync Github Prs to Notion
    
on:
  issues:
    types: [opened, edited, deleted, transferred, pinned, unpinned, closed, reopened, assigned, unassigned, labeled, unlabeled, locked, unlocked, milestoned, demilestoned]
  pull_request:
    types: [assigned, unassigned, labeled, unlabeled, opened, edited, closed, reopened, synchronize, converted_to_draft, ready_for_review, locked, unlocked, review_requested, review_request_removed, auto_merge_enabled, auto_merge_disabled]

permissions:
    contents: read
    issues: read
    pull-requests: read

jobs:
  sync:
    runs-on: ubuntu-latest
    environment: notion-sync
    steps:
    - uses: actions/checkout@v4

    - name: Sync Github PRs to Notion
      uses: sivashanmukh/github-notion-pr-sync@v1
      with:
        notionKey: ${{ secrets.NOTION_KEY }} 
        notionDatabaseId: ${{ secrets.NOTION_DATABASE_ID }}
        githubKey: ${{ github.token }}
